# Generated by Django 6.0.4 on 2026-04-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('contacts', models.CharField(help_text='Phone number, address', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('social_media', models.CharField(help_text='LinkedIn, GitHub, etc.', max_length=200)),
                ('specialization', models.CharField(help_text='e.g. Software Engineer', max_length=100)),
                ('edu_start', models.DateField(help_text='Start Date')),
                ('edu_end', models.DateField(help_text='End Date')),
                ('edu_institution', models.CharField(help_text='University Name', max_length=150)),
                ('edu_degree', models.CharField(help_text='Degree Name', max_length=150)),
                ('exp_start', models.DateField(help_text='Start Date')),
                ('exp_end', models.DateField(help_text='End Date')),
                ('exp_employer', models.CharField(max_length=150)),
                ('exp_position', models.CharField(max_length=150)),
                ('skills', models.TextField(help_text='Comma-separated list of skills')),
                ('photo', models.ImageField(upload_to='resume_photos/')),
                ('languages', models.CharField(help_text='Comma-separated languages', max_length=200)),
                ('extra_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
